#!/bin/sh

BTVOLUMES=/dev:/tmp:/home:/opt:/usr/share/applications:/usr/share/desktop-directories:/etc/xdg:/var/BlackmagicDesign:/usr/lib/udev/rules.d

MOUNTS=''
for volume in `echo "$VOLUMES" "$BTVOLUMES" | tr ':' ' '`
do
    MOUNTS="$MOUNTS --mount type=bind,source=$volume,destination=$volume"
done
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/passwd > /tmp/users
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/group > /tmp/groups
docker run $MOUNTS --mount type=bind,source=/opt/drinstaller/lib64/lib,destination=/usr/lib64/lib -u 0:0 -e HOME="$HOME" -e DISPLAY="$DISPLAY" -ti ghcr.io/shachar/davinciresolve-rocky:latest /opt/drinstaller/scripts/actual_wrapper "$USER" "$@"
