#!/bin/sh

UID=`id -u`
GID=`id -g`
BTVOLUMES=/dev:/tmp:/home:/opt:/usr/share/applications:/usr/share/desktop-directories:/etc/xdg:/var/BlackmagicDesign:/usr/lib/udev/rules.d

MOUNTS=''
for volume in `echo "$VOLUMES" "$BTVOLUMES" | tr ':' ' '`
do
    MOUNTS="$MOUNTS --mount type=bind,source=$volume,destination=$volume"
done

GROUPS=''
for group in `id -G`
do
    GROUPS="$GROUPS --group-add=$group"
done

docker run --runtime=nvidia --gpus all $MOUNTS --mount type=bind,source=/opt/drinstaller/lib64/lib,destination=/usr/lib64/lib -u $UID:$GID $GROUPS -e HOME="$HOME" -e DISPLAY="$DISPLAY" -w "`pwd`" ghcr.io/shachar/davinciresolve-rocky:latest "$@"
