#!/bin/sh -e

REAL_USER="$1"
shift

cat /tmp/users >> /etc/passwd
rm /tmp/users
cat /tmp/groups >> /etc/group
rm /tmp/groups
chmod 4755 /usr/bin/pkexec

su - $REAL_USER /opt/drinstaller/scripts/unprivileged_wrapper "$DISPLAY" "$@"
