#!/bin/sh -e

INSTALLER="$1"
if [ -z "$1" ]
then
    echo "Please provide path to DaVinci Resolve installer"
    read INSTALLER
fi

# INSTALLER is sometimes needlessly quoted
SANITIZED="`echo "$INSTALLER" | sed -e '{ s/^"\(.*\)"$/\1/ ; s/^'\''\(.*\)'\''$/\1/ }'`"

echo distrorun --extra-volume=/usr/lib/udev/rules.d drrocky "$SANITIZED"
distrorun --extra-volume=/usr/lib/udev/rules.d drrocky "$SANITIZED"

echo
echo "Post BlackMagic setup adjustments"

pkexec /opt/drinstaller/dr-installer-postsetup

for desktop in $HOME/Desktop/com.blackmagicdesign.*.desktop
do
    sed -i -e "s:^Exec=/opt/resolve:Exec=distrorun drrocky /opt/resolve:" "$desktop"
done

echo
echo "Installation done"
