#!/bin/sh -e
mkdir /srv/distros/rocky-8
cd /srv/distros/rocky-8
tar xvf ~shachar/sources/drinstaller-1.00/docker/Rocky-8-Container-x86_64-Base.tar.xz

# DNS resolver
cp /etc/resolv.conf etc/

# Custom users and groups
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/passwd >> etc/passwd
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/group >> etc/group

echo rocky-8 > etc/debian_chroot

cat >/etc/distrorun.d/rocky-8.conf <<EOF
dir: "/srv/distros/rocky-8"
mapped_volumes: [
    "/dev",
    "/home",
    "/run",
    "/tmp"
]
EOF

cd /

distrorun rocky-8 dnf install -y \
        alsa-lib apr apr-util dbus-libs fontconfig freetype \
        libglvnd libglvnd-egl libglvnd-glx libglvnd-opengl libgomp \
        libICE librsvg2 libSM libX11 libXau libxcb libXcursor \
        libXext libXfixes libXi libXinerama libxkbcommon \
        libxkbcommon-x11 libXrandr libXrender libXtst libXxf86vm \
        mesa-libGLU mtdev pulseaudio-libs xcb-util \
        xcb-util-image xcb-util-keysyms xcb-util-renderutil \
        xcb-util-wm ocl-icd usbutils libXt \
        python39 polkit glibc-langpack-en libpng12 procps-ng \
        nss libxkbfile

distrorun rocky-8 dnf install -y epel-release
distrorun rocky-8 dnf install -y xcb-util-cursor

# Install all locales needed by the current shell
LOCALS="`locale | sed -e '{ s:.*="\(..\).*:\1: ; s:.*=\(..\).*:\1: ; s:LC_.*:: }' | sort -u | grep -v '^$'`"
for locale in $LOCALS
do
    distrorun rocky-8 dnf install -y glibc-langpack-$locale
done

# For installing the nvidia drivers
distrorun rocky-8 dnf install -y kmod util-linux fuse fuse-libs vulkan-loader pkgconfig libglvnd

# distrorun rocky-8 .../NVIDIA-Linux-x86_64-....run --no-kernel-modules
# driver version from dpkg: dpkg -l nvidia-driver\* | grep 'nvidia-driver-[0-9]\+' | tr -s ' ' | cut -d ' ' -f 3 | sed -e 's:\([0-9.]\+\).*:\1:'
# https://www.nvidia.com/download/driverResults.aspx/226768/en-us
# https://www.nvidia.com/content/DriverDownloads/confirmation.php?url=/XFree86/Linux-x86_64/550.90.07/NVIDIA-Linux-x86_64-550.90.07.run&lang=us&type=geforcem
# https://us.download.nvidia.com/XFree86/Linux-x86_64/550.90.07/NVIDIA-Linux-x86_64-550.90.07.run
#
# VER=`dpkg -l nvidia-driver\* | grep 'nvidia-driver-[0-9]\+' | tr -s ' ' | cut -d ' ' -f 3 | sed -e 's:\([0-9.]\+\).*:\1:'`
# wget https://us.download.nvidia.com/XFree86/Linux-x86_64/$VER/NVIDIA-Linux-x86_64-$VER.run
#
# VER=`nvidia-smi  | sed -ne '/Driver Version: /{s/.*Driver Version: \([0-9.]\+\)\s.*/\1/; p}'`
