#!/bin/sh -e

INSTDIR=/srv/distros/drrocky
RUNDIR=/opt/drinstaller

if [ -d "$INSTDIR" -a "$1" != "force" ]
then
    echo "$INSTDIR directory already exists. Either delete it or pass \"force\" as first argument" >&2

    exit 1
fi

mkdir -p "$INSTDIR"
cd "$INSTDIR"
tar xvf "$RUNDIR/Rocky-8-Container-x86_64-Base.tar.xz"
mkdir -p usr/share/fonts

# DNS resolver
cp /etc/resolv.conf etc/

# Custom users and groups
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/passwd >> etc/passwd
sed -ne '/[^:]*:1[0-9]\{3\}:/p' /etc/group >> etc/group

echo drrocky > etc/debian_chroot

cd /

distrorun drrocky dnf install -y \
        alsa-lib apr apr-util dbus-libs fontconfig freetype \
        libglvnd libglvnd-egl libglvnd-glx libglvnd-opengl libgomp \
        libICE librsvg2 libSM libX11 libXau libxcb libXcursor \
        libXext libXfixes libXi libXinerama libxkbcommon \
        libxkbcommon-x11 libXrandr libXrender libXtst libXxf86vm \
        mesa-libGLU mtdev pulseaudio-libs xcb-util \
        xcb-util-image xcb-util-keysyms xcb-util-renderutil \
        xcb-util-wm ocl-icd usbutils libXt \
        python39 polkit glibc-langpack-en libpng12 procps-ng \
        nss libxkbfile alsa-plugins-pulseaudio alsa-ucm

distrorun drrocky dnf install -y epel-release
distrorun drrocky dnf install -y xcb-util-cursor

# Install all locales needed by the current shell
LOCALS="`locale | sed -ne '/^L.*=../{ s:.*="\(..\).*:\1: ; s:.*=\(..\).*:\1: ; s:LC_.*:: ; p }' | sort -u | grep -v '^$'`"
if [ -n "$LOCALS" ]
then
    for locale in $LOCALS
    do
        distrorun drrocky dnf install -y glibc-langpack-$locale
    done
fi

# For installing the nvidia drivers
distrorun drrocky dnf install -y kmod util-linux fuse fuse-libs vulkan-loader pkgconfig libglvnd

# Mark the rocky image version
echo 1 > $INSTDIR/etc/drinstaller.ver
